default[:leiningen][:version] = "2.0.0-preview10"
default[:leiningen][:install_script] = "https://github.com/technomancy/leiningen/raw/#{leiningen[:version]}/bin/lein"
default[:leiningen][:jar_url] = "http://github.com/downloads/technomancy/leiningen/leiningen-#{leiningen[:version]}-standalone.jar"
default[:leiningen][:jar_checksum] = "96ec431d13a2ca61adc0858b1ec77e64"
default[:leiningen][:jar_dir] = "/usr/share/java"
